# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            coding me swiftly
tagline:          ''
description:      'making code elegant by mdomans'
url:              http://mdomans.github.io
baseurl:          /

author:
  name:           'Michael Domanski'
  url:            https://twitter.com/mdomans

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mdomans
